FROM golang:1.11 as builder
RUN mkdir -p /root/go/src/github.com/freepk/epoll
WORKDIR /root/go/src/github.com/freepk/epoll
ADD ./epoll.go ./
RUN go clean && go build epoll.go

FROM ubuntu
COPY --from=builder /root/go/src/github.com/freepk/epoll/epoll /epoll
ENV GOGC=off
CMD ["/epoll"]
